//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\ama\source\repos\arbolGenealogico\arbolGenealogico.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="arbolGenealogicoParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IarbolGenealogicoVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="arbolGenealogicoParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] arbolGenealogicoParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="arbolGenealogicoParser.descendencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDescendencia([NotNull] arbolGenealogicoParser.DescendenciaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="arbolGenealogicoParser.hijos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHijos([NotNull] arbolGenealogicoParser.HijosContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="arbolGenealogicoParser.matrimonio"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMatrimonio([NotNull] arbolGenealogicoParser.MatrimonioContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="arbolGenealogicoParser.persona"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPersona([NotNull] arbolGenealogicoParser.PersonaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="arbolGenealogicoParser.fallecido"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFallecido([NotNull] arbolGenealogicoParser.FallecidoContext context);
}
