//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\ama\source\repos\arbolGenealogico\arbolGenealogicoV2.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="arbolGenealogicoV2Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IarbolGenealogicoV2Visitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="arbolGenealogicoV2Parser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] arbolGenealogicoV2Parser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="arbolGenealogicoV2Parser.descendencia"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDescendencia([NotNull] arbolGenealogicoV2Parser.DescendenciaContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="arbolGenealogicoV2Parser.hijos"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHijos([NotNull] arbolGenealogicoV2Parser.HijosContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>familia</c>
	/// labeled alternative in <see cref="arbolGenealogicoV2Parser.matrimonio"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFamilia([NotNull] arbolGenealogicoV2Parser.FamiliaContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>jamon</c>
	/// labeled alternative in <see cref="arbolGenealogicoV2Parser.matrimonio"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJamon([NotNull] arbolGenealogicoV2Parser.JamonContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>fallecido</c>
	/// labeled alternative in <see cref="arbolGenealogicoV2Parser.persona"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFallecido([NotNull] arbolGenealogicoV2Parser.FallecidoContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>vivo</c>
	/// labeled alternative in <see cref="arbolGenealogicoV2Parser.persona"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVivo([NotNull] arbolGenealogicoV2Parser.VivoContext context);
}
